name: 'Push to DigitalOcean'
description: 'Make a Digital Ocean droplet and push docker image in it'
inputs:
  token:  # id of input
    description: 'Digital Ocean token'
    required: true
    default: 'digitalOceanDeveloperToken'
  name:  # id of input
    description: 'Name of the droplet to be build'
    required: true
    default: 'fromgithub'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    token: ${{ inputs.token }}
    name: ${{ inputs.name }}
