name: 'Push to DigitalOcean'
description: 'Make a Digital Ocean droplet and push docker image in it'
inputs:
  token:  # id of input
    description: 'Digital Ocean token'
    required: true
    default: 'digitalOceanDeveloperToken'
  name:  # id of input
    description: 'Name of the droplet to be build'
    required: false
    default: 'fromgithub'
  ports:  # id of input
    description: 'Ports parameters, passing to docker image'
    required: true
    default: '80:80'
  image:  # id of input
    description: 'Name of the image'
    required: true
    default: 'dockerimage'
  file:  # id of input
    description: 'Name of the file'
    required: true
    default: 'dockerimage.tgz'
  monitoring:  # id of input
    description: 'Enable monitoring'
    required: false
    default: true
  fingerprint:  # id of input
    description: 'ssh fingerprint'
    required: false
    default: ''
  private_key:  # id of input
    description: 'private_key content'
    required: false
    default: ''    
  public_key:  # id of input
    description: 'public_key content'
    required: false
    default: ''
outputs:
  ip: # id of output
    description: 'Droplet ip'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    token: ${{ inputs.token }}
    name: ${{ inputs.name }}
    ports: ${{ inputs.ports }}
    image: ${{ inputs.image }}
    file: ${{ inputs.file }}
    fingerprint: ${{ inputs.fingerprint }}
    private_key: ${{ inputs.private_key }}
    public_key: ${{ inputs.public_key }}
